sudo: required

language: php

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

env:
  global:
    - EE_VERSION=master
    - WP_VERSION=latest WP_MULTISITE=0

before_install:
   - nvm install && nvm use
   - |
      if [[ "$SKIP_XDEBUG_REMOVE" != "true" ]]; then
        cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
        phpenv config-rm xdebug.ini
        echo "xdebug removed";
      fi

before_script:
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - . tests/bin/setup-addon-tests.sh
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    # Install the specified version of PHPUnit depending on the PHP version:
    if [[ -n "$TRAVIS_PHP_VERSION" ]]; then
      case "$TRAVIS_PHP_VERSION" in
        7.2|7.1|7.0|nightly)
          echo "Using PHPUnit 6.1"
          composer global require "phpunit/phpunit=6.1.*"
          ;;
        5.6|5.5|5.4|5.3)
          echo "Using PHPUnit 4.8"
          composer global require "phpunit/phpunit=4.8.*"
          ;;
        5.2)
          # Do nothing, use default PHPUnit 3.6.x
          echo "Using default PHPUnit, hopefully 3.6"
          ;;
        *)
          echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
          exit 1
          ;;
      esac
    fi
  - mysql --version
  - phpunit --version
  - phpenv versions

script: npm run test-php

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.2
      env:
        - PHP_LINT=1
        - PHP_LINT_WITH_WARNINGS=yes
  include:
    - stage: test
      php: 7.2
      env:
        - PHP_LINT=1
        - PHP_LINT_WITH_WARNINGS=no
      script:
        - composer install || exit 1
        - composer config-eventespressocs || exit 1
        - npm run lint-php:skip-warnings || exit 1
    - php: 7.2
      env:
        - PHP_LINT=1
        - PHP_LINT_WITH_WARNINGS=yes
      script:
        - composer install || exit 1
        - composer config-eventespressocs || exit 1
        - npm run lint-php || exit 1
## skipping for now because there's no javascript to test!
#    - env:
#        - JAVASCRIPT_TESTS=1
#      script:
#        - npm install || exit 1
#        - npm run ci || exit 1
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    # multisite
    - php: 7.2
      env: WP_MULTISITE=1
    - php: 7.1
      env: WP_MULTISITE=1
    - php: 7.0
      env: WP_MULTISITE=1
    - php: 5.6
      env: WP_MULTISITE=1
    # wp 4.5 builds
    - php: 5.6
      env: WP_VERSION=4.5
    - php: 5.6
      env: WP_VERSION=4.5 WP_MULTISITE=1
    - php: nightly

notifications:
  slack:
    rooms:
      secure: "IFcYpKomnKcbXLblKIFtsjclbsYoqhQWzzLyO4qdVBlopRWnwwhYUoIMLtgBKNq2+NvmllLp2mFV806BYIirhfQGqjjeLDeBSd52FVZgLU5hRKfHtz3/LjsJpweVgX3KT46NrEBycoH5yB21obSUrJf0ry1+GuY+EaK6KF5gUqLeWgZAllkVxVJcp2UWCG1c0sHCKrLwQD0NJywx2SvWLeBj16ehn1GLTExUMoxQX/HPmjgOGxQJMh3hQGViSnAckOX4vl0Jh7N2vL6n9Nkod8KUioX4r8HBKJ8wQlIPbASnFOTGDzShCC+QagrRg/hlFY2/WB28gk88rkUiLmo8oxUOzOAhOpTAefGiOfZUIQLsv6C7wQ8H19v6R8u0m+4jHLg4WTAGM8uL0q0jX1kL1XYvdE9yAjRuX51H+sz6L4uucygocCSyxvAIMlGy0a4FMXO2TzJ081aixZB1Sh7hggcadQJtoxNiEPDegvAzPnza7q2KjpxrzkgRHxtkqK4Y2qY8t46aGpF06+Dmlq0+faAJ04kaR9Vi/wLfFMxmrh73wodupP7FYS/FZeoqSLsA19UHXH7IDhrqVSXoxBBAg8qlciqiFcS72VMjk9Le2CIkMjSBa4H/gomon1y7xT8a+mx48pM5ME550NRRNDA1LR3PJIOP4xxleDcdEP4WyBY="
    on_success: change
    on_failure: always
    on_start: always
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
      - "%{commit_message}"

